hspd = 0
vspd = 0
spd = 1
dir = "up"
var seg = 45
time_mov = seg * 2
alarm[0] = time_mov
mov_little = noone
mov_big = noone
time_ev = seg*4
alarm[1] =time_ev
turned = false
substate = gun_sub_state
drop = noone
adubo = 0
alarm[2] = 45*30
